# Generated by Django 5.1.2 on 2025-03-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=32, unique=True, verbose_name='用户名')),
                ('name', models.CharField(blank=True, help_text='昵称', max_length=32, null=True, verbose_name='用户昵称')),
                ('birthday', models.CharField(blank=True, help_text='生日', max_length=32, null=True, verbose_name='用户生日')),
                ('groupid', models.IntegerField(choices=[(1, '超级管理员'), (2, '普通用户')])),
                ('password', models.CharField(help_text='密码', max_length=64, verbose_name='密码')),
                ('phone', models.CharField(help_text='手机号', max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, null=True, verbose_name='邮箱')),
                ('reg_time', models.DateTimeField(auto_now_add=True, help_text='注册时间', verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, help_text='最近登录时间', verbose_name='最近登录时间')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='交易名称', max_length=100, verbose_name='交易名称'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='交易金额', max_digits=10, verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='交易名称(去向)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.category', verbose_name='交易名称'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='交易时间', verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='交易详情描述', verbose_name='交易详情描述'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Income'), (2, 'Expense')], help_text='交易类型', verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='accounting.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='accounting.user', verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
