# Generated by Django 5.1.2 on 2025-04-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_user_alter_category_name_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupid',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '普通用户')], default=1),
        ),
    ]
