# Generated by Django 5.1.2 on 2025-04-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_user_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='17854228733', help_text='手机号', max_length=11, verbose_name='手机号码'),
        ),
    ]
