# Generated by Django 5.1.2 on 2025-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='手机号', max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
