# Generated by Django 5.1.2 on 2025-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupid',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '普通用户')], default=2),
        ),
    ]
