# Generated by Django 5.1.2 on 2025-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_user_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='交易详情描述', null=True, verbose_name='交易详情描述'),
        ),
    ]
