# Generated by Django 5.1.2 on 2025-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='用户名', max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
