# Generated by Django 5.1.2 on 2025-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='交易日期', verbose_name='交易日期'),
        ),
    ]
